http local {
    endpoints { "/dns-query"; };
};

options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { any; };
    recursion yes;
};

include "/etc/bind/named.conf.local";
