events {}
http {
  # HTTP - Chuyển hướng sang HTTPS và hỗ trợ Certbot challenge
  server {
    listen 80;
    server_name tnb.io.vn www.tnb.io.vn;

    location /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 301 https://$host$request_uri;
    }
  }

  # HTTPS - Cấu hình SSL chính thức
  server {
    listen 443 ssl;
    server_name tnb.io.vn www.tnb.io.vn;

    ssl_certificate /etc/letsencrypt/live/tnb.io.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tnb.io.vn/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
      proxy_pass http://c1-sa-web:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
